global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'sre-chaos-app'
    static_configs:
      - targets: ['sre-chaos-app:8000'] # Usamos el nombre del contenedor dentro de la red sre-network
